### ISSUE TITLE
face cascade detection issu

### ISSUE THREAD

**Issue by bimbimprasetyoafif** [D3-IT-B-EEPIS-2018/CompVist#4]
tolong coba cek ini teman2, kayak nya aq run file yang cropface.py dan dapat error ini

faces = face_cascade.detectMultiScale(gray, 1.3, 5)
cv2.error: OpenCV(4.2.0) /io/opencv/modules/objdetect/src/cascadedetect.cpp:1689: error: (-215:Assertion failed) !empty() in function 'detectMultiScale'

ada yg salah kah?

**Comment by anidast** [comment]
sudah ditambahi file haarcascade_frontalface_default.xml
done.
